export const en = { 
    eDiamante: () => '💎', eExp: () => '⚡', eDiamantePlus: () => '💎+', eMagia: () => '🌀', eToken: () => '🪙', eEsmeralda: () => '💚', eEnergia: () => '✨', eOro: () => '👑', eBasura: () => '🗑', eHierro: () => '⛓️', eRoca: () => '🪨', ePocion: () => '🥤', eMadera: () => '🪵', eEspada: () => '⚔️', eCComun: () => '📦', ePComun: () => '🥡', eCMistica: () => '🗳️', eClegendaria: () => '🎁', eAMascots: () => '🍖', eCMascota: () => '🍱', eSUva: () => '🍇', eSManzana: () => '🍎', eSNaranja: () => '🍊', eSMango: () => '🥭', eSPlatano: () => '🍌', eUva: () => '🍇', eManzana: () => '🍎', eNaranja: () => '🍊', eMango: () => '🥭', ePlatano: () => '🍌', eCentauro: () => '🐐', eAve: () => '🦅', eGato: () => '🐈', eDragon: () => '🐉', eZorro: () => '🦊', eCaballo: () => '🐎', eFenix: () => '🕊️', eLobo: () => '🐺', ePerro: () => '🐶', eCCentauro: () => '🐐🥩', eCAve: () => '🦅🥩', eCMagica: () => '🌀🥩', eCDragon: () => '🐉🥩', eACaballo: () => '🍱🥩', eCFenix: () => '🕊️🥩', eJoya: () => '♦️', eEllCoins: () => '🤖', eEllTickers: () => '🎫', eAgua: () => '💧', ePiedra: () => '🥌', eCuerda: () => '🕸️', eCarbon: () => '⚱️', eBotella: () => '🍶', eLata: () => '🥫', eCarton: () => '🪧', eEletric: () => '💡', eBarraOro: () => '〽️', eOroComun: () => '🧭', eZorroG: () => '🦊🌫️', eBasuraG: () => '🗑🌫️', eLoboG: () => '🐺🌫️', eMaderaG: () => '🛷', eCarnada: () => '🪱', eBillete: () => '💵', ePinata: () => '🪅', eGancho: () => '🪝', eCanaPescar: () => '🎣', eCJardineria: () => '💐',
    smsCont1: () => "❌ Terjadi error pada plugin",
    smsCont2: () => "📝 Plugin:",
    smsCont3: () => "👤 Pengirim:",
    smsCont4: () => "💬 Pesan:",
    smsCont5: () => "⚠️ Error:",
    smsCont6: () => "Lapor owner jika ini berlanjut.",
    smsCont7: () => "❌ Limit harian Anda habis. Silakan beli limit dengan",
    smsCont8: () => " Limit terpakai.",
    smsCont9: () => "🆙 Level diperlukan:",
    smsCont10: () => "Level Anda saat ini:",
    smsCont11: () => "Ketik menu untuk info lebih lanjut.",
    smsCont15: () => "📞 Panggilan terdeteksi.",
    smsCont16: () => "Video call",
    smsCont17: () => "Voice call",
    smsCont18: () => "Bot tidak menerima panggilan, Anda akan diblokir otomatis.",
    smsCont19: () => "ANTIDELETE",
    smsCont20: () => "Pesan dihapus oleh",
    smsCont21: () => "Berikut adalah isi pesannya:",
    smsRowner: () => "Fitur ini hanya untuk Real Owner.",
    smsOwner: () => "Fitur ini hanya untuk Owner.",
    smsMods: () => "Fitur ini hanya untuk Moderator.",
    smsPremium: () => "Fitur ini hanya untuk User Premium.",
    smsGroup: () => "Fitur ini hanya dapat digunakan di dalam Grup.",
    smsPrivate: () => "Fitur ini hanya dapat digunakan di Private Chat.",
    smsAdmin: () => "Fitur ini hanya untuk Admin Grup.",
    smsBotAdmin: () => "Bot harus menjadi Admin untuk menggunakan fitur ini.",
    smsUnreg: () => "Silakan daftar terlebih dahulu untuk menggunakan fitur ini.",
    smsRestrict: () => "Fitur ini dinonaktifkan oleh Owner.",
    smsAvisoAG: () => "⚠️ PERINGATAN ⚠️"
};
export const es = { ...en };
export const ar = { ...en };
export const id = { ...en };
export const pt = { ...en };
