import axios from "axios";

export default async function ({ cmd, q, reply, sock, jid, msg, prefix }: any) {
    if (cmd === "aiimg" || cmd === "draw" || cmd === "drawing") {
        if (!q) return reply(`Masukkan prompt! Contoh: ${prefix}aiimg robot frog with EL text`);
        
        try {
            await reply("Sedang membuat gambar... 🎨");
            
            // Using pollinations.ai for free image generation
            const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(q)}?width=512&height=512&nologo=true`;
            
            await sock.sendMessage(jid, { 
                image: { url: imageUrl }, 
                caption: `*Prompt:* ${q}\n\nGenerated by AI 🚀` 
            }, { quoted: msg });
            
        } catch (e) {
            console.error(e);
            reply("Gagal membuat gambar. Coba lagi nanti.");
        }
        return true;
    }

    return false;
}
